### ISSUE TITLE
Linking.getInitialURL() always returning null in IOS when notification open the app

### ISSUE THREAD

**Issue by youcefswoo** [klaviyo/klaviyo-react-native-sdk#140] opened 2024-04-02 16:03 UTC
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] I have determined whether this bug is also reproducible in a vanilla project, such as the example app in this repository.
- [X] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)

### Description

```markdown
After following the documentation and the example in the repository, I began testing to see if I could receive the deep link when the app is killed. In Android, it works well, but in iOS, Linking.getInitialURL() always returns null.
```

### Expected behavior

```markdown
I expected to receive the deep link that I placed in the deep link section of the notification definition.
```

### Actual behavior

```markdown
Linking.getInitialURL() always returns null in iOS when a notification is clicked.
```

### Steps to reproduce

```markdown
1. Create a notification with a deep link for IOS.
2. Click on the notification to open the application.
```

### The Klaviyo React Native SDK version information

0.3.0

### Environment Description

Using real device (iPhone 12 . IOS 16.6.1)
react native 0.73.3

**Comment by ajaysubra** [comment] 2024-04-02 16:12
@youcefswoo Couple questions - 
1. Can you confirm that you followed the [instructions](https://github.com/klaviyo/klaviyo-react-native-sdk/tree/master?tab=readme-ov-file#deep-linking) from the readme?
2. Are you able to reproduce this issue using the example app here?

When we published the example iOS app, we tested and deep linking was working but does involve some intricate setup for iOS outlined in the readme.

**Comment by youcefswoo** [comment] 2024-04-02 18:34
> @youcefswoo Couple questions -
> 
> 1. Can you confirm that you followed the [instructions](https://github.com/klaviyo/klaviyo-react-native-sdk/tree/master?tab=readme-ov-file#deep-linking) from the readme?
> 2. Are you able to reproduce this issue using the example app here?
> 
> When we published the example iOS app, we tested and deep linking was working but does involve some intricate setup for iOS outlined in the readme.

@ajaysubra 
1. Yes, I took all the time to follow the instructions and I double-checked all the steps multiple times. For the options, I used the first one since it is faster and easier.
2. Yes, I executed the example. I only changed the `Bundle Identifier` to match the bundle existing in my Klaviyo account so I can receive the notification. I created some test campaigns with `rntest://` as a deep link. When I click the notification, it opens the app, but I always get null from getInitialURL.

**Comment by kennyklaviyo** [comment] 2024-04-02 18:57
@youcefswoo You mention `getInitialURL()` returning `null`, is your app in the background when you're clicking on the push notification? Or is the app killed when you click on the push notification? The README points out [another method](https://github.com/klaviyo/klaviyo-react-native-sdk?tab=readme-ov-file#deep-linking:~:text=Linking.addEventListener(%27url%27%2C%20(event)%20%3D%3E%20%7B%0A%20%20console.log(event.url)%3B%0A%7D)%3B) of getting the deep link: `Linking.addEventListener(...)`. Have you looked at what that returns?

**Comment by youcefswoo** [comment] 2024-04-02 19:15
> @youcefswoo You mention `getInitialURL()` returning `null`, is your app in the background when you're clicking on the push notification? Or is the app killed when you click on the push notification? The README points out [another method](https://github.com/klaviyo/klaviyo-react-native-sdk?tab=readme-ov-file#deep-linking:~:text=Linking.addEventListener(%27url%27%2C%20(event)%20%3D%3E%20%7B%0A%20%20console.log(event.url)%3B%0A%7D)%3B) of getting the deep link: `Linking.addEventListener(...)`. Have you looked at what that returns?

In all my tests, the app was terminated. The `addEventListener` is used for real-time clicks when the app is in the background or foreground. However, when the app is terminated, the only way to retrieve the deep link that triggers the app to open is by using `getInitialURL()`.

**Comment by ajaysubra** [comment] 2024-04-02 21:31
@youcefswoo I just tested using the example app using both option 1 and 2. With option 1, the application delegate [application(_:open:options)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application) is correctly getting called and as for option 2 I am seeing the SDK correctly calling the callback passed when you call the handle method on iOS. Outside of this, our SDK doesn't do anything as it pertains to deep linking. Some options that I would debug are, 

1. Be sure that the installation step 2 from the iOS example appedelegate is done in your app and that you are not passing in the `deepLinkHandler` when calling the SDK `handle` method. If you pass in the `deepLinkHandler` that will be called and the application delegate [application(_:open:options)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application) will not. 
2. If the above is setup correctly, I would add a print statement in [application(_:open:options)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application) and see if the url is being printed there. 

Please try these out and let us know.

**Comment by youcefswoo** [comment] 2024-04-03 11:55
@ajaysubra I managed to reproduce the issue in the example project, as mentioned above. Therefore, I don't believe the issue is related to my configuration. I just want to confirm whether you tested the process with a real Klaviyo notification, or if you simply clicked on a deep link, or if you executed this command: `npx uri-scheme open "MY_DEEP_LINK" --ios`.

**Comment by ajaysubra** [comment] 2024-04-03 14:53
Hey @youcefswoo I missed the part about the app being killed when you receive the push notification when testing yesterday. Sorry about that. I will look into this today and get back to you.

**Comment by ajaysubra** [comment] 2024-04-04 03:15
Hey @youcefswoo You were right, when the example iOS app is killed and a push deep link is received the `getInitialURL`  is printing `null`. It's not clear what is causing this, as far as the iOS side is concerned,  [application(_:open:options)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application) is getting called when a push is received and from that point onwards it's up to `RCTLinkingManager` to call the appropriate callback on the react native side. 

We will look into this further and get back to you.

**Comment by chinleung** [comment] 2024-04-10 13:41
Hey @ajaysubra,

Do you have any update or ETA for the issue here? 😄

**Comment by ajaysubra** [comment] 2024-04-10 13:47
@chinleung Unfortunately no updates yet. Should have an update by end of next week. Appreciate the patience.

**Comment by chinleung** [comment] 2024-04-10 13:49
> @chinleung Unfortunately no updates yet. Should have an update by end of next week. Appreciate the patience.

Perfect, thanks for the update!

**Comment by ajaysubra** [comment] 2024-04-15 19:22
Hey @youcefswoo @chinleung:  After doing some digging turns out this is an issue with react native. There are many open issues on their Github issues page but [this](https://github.com/facebook/react-native/issues/32350) is the most recent one. The best explanation I found of the issue was [this](https://github.com/facebook/react-native/issues/28727#issuecomment-847273118). I tried several of the workaround but many of them are for older versions of react native and no longer valid, but one workaround that I retro fitted to newer versions of react native was to add the key `UIApplicationLaunchOptionsURLKey` to the launch arguments before calling super method in `application:didFinishLaunchingWithOptions:`. This approach worked and calls the react native initial url listener! 

I created a PR that demonstrates this fix and updated the troubleshooting guide for reference [here](https://github.com/klaviyo/klaviyo-react-native-sdk/pull/148). Please try it out and let me know how it goes. Thanks!

**Comment by youcefswoo** [comment] 2024-04-15 20:05
@ajaysubra  I integrated the solution from the PR, and it works in all phone states. Thank you for your support.

**Comment by ajaysubra** [comment] 2024-04-15 20:12
Perfect. Closing this issue now!

**Closed by ajaysubra** 2024-04-15 20:12 UTC
Labels: bug

**Comment by ajaysubra** [comment] 2024-04-16 22:18
Hey, just FYI - I added a note [here](https://github.com/klaviyo/klaviyo-react-native-sdk/pull/148#discussion_r1567996044) as to why this workaround works.
